version: "3.7"

services:
  app:
    container_name: ship_it_app
    build: .
    image: ship_it:latest
    restart: on-failure:3
    depends_on:
      - db
    ports:
    - "8085:8085"

  db:
    container_name: ship_it_db
    image: postgres:12
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_DB=shipit
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=CVHVuUhi9YbDbaMoWk6A7Kp9AA
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
