server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://ship_it_db_service:5432/ship_it_db
    username: master
    password: ydAPnmSzWvMvquvsEPhDEmYwBEKnw6jT
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-app-service:8081
