server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ship_it_db
    username: master
    password: ydAPnmSzWvMvquvsEPhDEmYwBEKnw6jT
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.codeperfection.com
          jwk-set-uri: http://localhost:8081/oauth2/jwks
