server.port = 8085

spring.datasource.url = jdbc:postgresql://db:5432/shipit
spring.datasource.username = master
spring.datasource.password = CVHVuUhi9YbDbaMoWk6A7Kp9AA
spring.jpa.hibernate.ddl-auto = validate
spring.jpa.open-in-view = false

jwt.secret = CgV7E?*@bG097Bh@fF!O0CvrO|89
jwt.expiration-millis = 86400000
